language: ruby
rvm:
- 2.0.0
- 2.1.2
deploy:
  provider: rubygems
  api_key:
    secure: RUvlR3yDjIyKtP8Q80dpnFZ2muxsOPt9kVRG6mx7IpavQ3qQkH/2Kl+Hwo/5YoodQACPhfxMludsW2WsXMoSomVQrIjNA7nK3mkBNJxTM+vFMXBLuyJ9GbpaK9lZzG1sHTyakCcw3ieWh27GYjHKvJuc6KjexmUicReXdrGNmqY=
  gem: blinkbox-common_messaging
  on:
    repo: blinkboxbooks/common_messaging.rb
    rvm: 2.1.2
    branch: master
